name: CI-CD-GKE

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

env:
  PROJECT_ID: project-272c4cdf-a525-43cc-be2
  PROJECT_NUMBER: 188720845531
  GKE_CLUSTER: hackathon-cluster
  GKE_ZONE: asia-south1-a

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/188720845531/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: github-actions-sa@project-272c4cdf-a525-43cc-be2.iam.gserviceaccount.com

      - uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for GCR
        run: gcloud auth configure-docker --quiet

      - name: Get GKE Credentials
        run: gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE

      # -------------------------
      # APPLICATION SERVICE
      # -------------------------
      - name: Build & Push application-service
        run: |
          docker build -t gcr.io/$PROJECT_ID/application-service:${{ github.sha }} ./application-service
          docker push gcr.io/$PROJECT_ID/application-service:${{ github.sha }}

      - name: Deploy application-service
        run: |
          kubectl set image deployment/application-service \
          application-service=gcr.io/$PROJECT_ID/application-service:${{ github.sha }}

      # -------------------------
      # PATIENT SERVICE
      # -------------------------
      - name: Build & Push patient-service
        run: |
          docker build -t gcr.io/$PROJECT_ID/patient-service:${{ github.sha }} ./patient-service
          docker push gcr.io/$PROJECT_ID/patient-service:${{ github.sha }}

      - name: Deploy patient-service
        run: |
          kubectl set image deployment/patient-service \
          patient-service=gcr.io/$PROJECT_ID/patient-service:${{ github.sha }}

      # -------------------------
      # ORDER SERVICE
      # -------------------------
      - name: Build & Push order-service
        run: |
          docker build -t gcr.io/$PROJECT_ID/order-service:${{ github.sha }} ./order-service
          docker push gcr.io/$PROJECT_ID/order-service:${{ github.sha }}

      - name: Deploy order-service
        run: |
          kubectl set image deployment/order-service \
          order-service=gcr.io/$PROJECT_ID/order-service:${{ github.sha }}

      - name: Verify Rollout
        run: |
          kubectl rollout status deployment/application-service
          kubectl rollout status deployment/patient-service
          kubectl rollout status deployment/order-service
